name: Generate Predictions

on:
  workflow_call:
    inputs:
      numerator:
        required: true
        type: number
      denominator:
        required: true
        type: number
      model-id:
        required: true
        type: string
      sample-only:
        required: false
        type: string
      SHA:
        required: true
        type: string

jobs:
  infer-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Print system details
        run: sudo lshw -short

      - name: checkout repo content
        uses: actions/checkout@v4


      - name: Print contents of the current directory
        run: ls -la

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-central-1

      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Run make install
        run: make install-prod
      
      # we need this step as ersilia will use the default conda environment to run the example model during `ersilia serve`
      # could get around this eventually if we only use conda for env management, but there are complexities around referencing a dev
      # package from within our own package which poetry makes a lot easier
      - name: set up conda
        run: |
          cd ersilia
          echo $CONDA/bin >> $GITHUB_PATH
          source $CONDA/etc/profile.d/conda.sh
          conda install -y python=3.10
          conda init
          python -m pip install -e .[test]
          pip install pyairtable
          cd ..

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Run Python script to generate predictions and upload to S3
        env:
          MODEL_ID: ${{ inputs.model-id }}
          SHA: ${{ inputs.SHA }}
          numerator: ${{ inputs.numerator }}
          sample-only: ${{ inputs.sample-only }}
          GITHUB_REPOSITORY: ${{ github.event.repository.full_name }}
        run: .venv/bin/python scripts/generate_predictions_with_aws_and_ersilia.py ci