name: Run Serving in Parallel

on:
  repository_dispatch:
    types: ["inference-complete"]

  workflow_dispatch:
    inputs:
      model:
        required: true
        type: string
      sha:
        required: true
        type: string
  
  workflow_run:
    workflows: ["Run Inference in Parallel"]
    types:
      - completed

permissions:
  contents: read

jobs:
  matrix-inference:
    strategy:
      matrix:
        # partition: [
        #  1,2,3,4,5,6,7,8,9,10,
        #  11,12,13,14,15,16,17,18,19,20,
        #  21,22,23,24,25,26,27,28,29,30,
        #  31,32,33,34,35,36,37,38,39,40,
        #  41,42,43,44,45,46,47,48,49,50
        # ]
        partition: [1,2]
    uses: ./.github/workflows/serve.yml
    with:
      model: ${{ github.event.client_payload.model-id }}
      sha: ${{ github.event.client_payload.sha }}
      partition: ${{ matrix.partition }}
    secrets: inherit
